### ISSUE TITLE
运行脚本出现以下错误，请问该怎么处理

### ISSUE THREAD

**Issue by 1353918285** [kwuking/TimeMixer#10]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda\envs\TimeMixer\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\anaconda\envs\TimeMixer\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\anaconda\envs\TimeMixer\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\anaconda\envs\TimeMixer\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\anaconda\envs\TimeMixer\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\anaconda\envs\TimeMixer\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\anaconda\envs\TimeMixer\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\YD\code\TimeMixer-main\run.py", line 139, in <module>
    exp.train(setting)
  File "E:\YD\code\TimeMixer-main\exp\exp_long_term_forecasting.py", line 132, in train
    for i, (batch_x, batch_y, batch_x_mark, batch_y_mark) in enumerate(train_loader):
  File "D:\anaconda\envs\TimeMixer\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "D:\anaconda\envs\TimeMixer\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\anaconda\envs\TimeMixer\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "D:\anaconda\envs\TimeMixer\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\anaconda\envs\TimeMixer\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda\envs\TimeMixer\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\anaconda\envs\TimeMixer\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\anaconda\envs\TimeMixer\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "D:\anaconda\envs\TimeMixer\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by kwuking** [comment]
你好，这个是因为pytorch的dataloader数据加载使用多进程，如果你是本地使用CPU测试，请将num_workers设置为0，use_gpu参数设置为false

**Comment by 1353918285** [comment]
感谢回答!!!!!，num_work设置为0完美的解决了问题，请问有什么方法能进一步解决必须将num_workers设置为0吗？

**Comment by kwuking** [comment]
> 感谢回答!!!!!，num_work设置为0完美的解决了问题，请问有什么方法能进一步解决必须将num_workers设置为0吗？

CPU执行是通常建议将num_workers设置0的，如果在gpu上可以把该参数放到默认配置。
