### ISSUE TITLE
运行short_term_forecast出现如下报错

### ISSUE THREAD

**Issue by jiali1204** [kwuking/TimeMixer#13]
bash .\scripts\short_term_forecast\M4\TimeMixer.sh

Args in experiment:
Namespace(task_name='short_term_forecast', is_training=1, model_id='m4_Monthly', model='TimeMixer', data='m4', root_path='./dataset/m4', data_path='ETTh1.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=96, seasonal_patterns='Monthly', inverse=False, top_k=5, num_kernels=6, enc_in=1, dec_in=1, c_out=1, d_model=32, n_heads=4, e_layers=4, d_layers=1, d_ff=32, moving_avg=25, factor=3, distil=True, dropout=0.1, embed='timeF', activation='gelu', output_attention=False, channel_independence=1, decomp_method='moving_avg', use_norm=1, down_sampling_layers=1, down_sampling_window=2, down_sampling_method='avg', num_workers=10, itr=1, train_epochs=50, batch_size=128, patience=20, learning_rate=0.01, des='Exp', loss='SMAPE', lradj='TST', pct_start=0.2, use_amp=False, comment='none', use_gpu=False, gpu=0, use_multi_gpu=False, devices='0,1', p_hidden_dims=[128, 128], p_hidden_layers=2)
Use CPU
>>>>>>>start training : short_term_forecast_m4_Monthly_none_TimeMixer_m4_sl96_pl96_dm32_nh4_el4_dl1_df32_fc3_ebtimeF_dtTrue_Exp_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 48000
val 48000
Traceback (most recent call last):
  File "..\code\TimeMixer\run.py", line 139, in <module>
    exp.train(setting)
  File "..\code\TimeMixer\exp\exp_short_term_forecasting.py", line 95, in train
    outputs = self.model(batch_x, None, dec_inp, None)
  File "C:\ProgramData\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "..\code\TimeMixer\models\TimeMixer.py", line 383, in forward
    dec_out_list = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
  File "..\code\TimeMixer\models\TimeMixer.py", line 316, in forecast
    x_enc, x_mark_enc = self.__multi_scale_process_inputs(x_enc, x_mark_enc)
  File ..\TimeMixer\models\TimeMixer.py", line 304, in __multi_scale_process_inputs
    x_mark_sampling_list.append(x_mark_enc_mark_ori[:, ::self.configs.down_sampling_window, :])
TypeError: 'NoneType' object is not subscriptable

**Comment by kwuking** [comment]
你好 我这边刚使用CPU测试了M4数据集是没有出现上述报错的，请问您的环境配置是否参照requirements配置正确呢？下面是截取的一个epoch的日志：
Use CPU
>>>>>>>start training : short_term_forecast_m4_Monthly_TimeMixer_m4_ftM_sl36_ll18_pl18_dm32_nh8_el4_dl1_df32_fc3_ebtimeF_dtTrue_'Exp'_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 48000
val 48000
	iters: 100, epoch: 1 | loss: 7.8308382
	speed: 0.2601s/iter; left time: 4851.6192s
	iters: 200, epoch: 1 | loss: 8.6521778
	speed: 0.0851s/iter; left time: 1579.3541s
	iters: 300, epoch: 1 | loss: 7.9615688
	speed: 0.0867s/iter; left time: 1599.4812s
Epoch: 1 cost time: 99.35813999176025
