### ISSUE TITLE
  B, T, N = x.size()出错

### ISSUE THREAD

**Issue by t8115** [kwuking/TimeMixer#20]
Traceback (most recent call last):
  File "E:/PyCharm Community Edition 2023.2.4/plugins/python-ce/helpers/pydev/pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\PyCharm Community Edition 2023.2.4\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\ Time-Series-Library-main\Times_Series_Lib\new_main.py", line 36, in <module>
    main()  #模型训练和测试
  File "D:\ Time-Series-Library-main\Times_Series_Lib\Model.py", line 164, in main
    exp.train(setting)
  File "D:\ Time-Series-Library-main\Times_Series_Lib\exp\exp_long_term_forecasting.py", line 133, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "E:\anaconda\envs\pytorch-38\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\anaconda\envs\pytorch-38\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ Time-Series-Library-main\Times_Series_Lib\models\TimeMixer.py", line 384, in forward
    dec_out_list = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
  File "D:\ Time-Series-Library-main\Times_Series_Lib\models\TimeMixer.py", line 324, in forecast
    B, T, N = x.size()
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by kwuking** [comment]
你好 请问你是执行哪个脚本报错的？

**Comment by t8115** [comment]
我是运行run文件，
![微信图片_20240422114512](https://github.com/kwuking/TimeMixer/assets/106149523/730e0c76-9bdf-40f9-92d1-1e36bb8d39d2)
我通过调试代码，发现每次遍历zip是，x，x_mark是二维的，但是B, T, N = x.size()是要求三维的，然后就出现错误了

**Comment by calamityttc** [comment]
我也是

**Comment by kwuking** [comment]
@t8115 @calamityttc 如果是在pycharm里面执行的话，请把运行参数给一下，具体执行的是哪个脚本？

**Comment by kwuking** [comment]
> @t8115 @calamityttc 如果是在pycharm里面执行的话，请把运行参数给一下，具体执行的是哪个脚本？

@t8115 @calamityttc 可以参考这个[issue](https://github.com/kwuking/TimeMixer/issues/2)
