### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by onlyuwannn01** [kwuking/TimeMixer#28]
Traceback (most recent call last):
  File "run.py", line 143, in <module>
    exp.train(setting)
  File "/root/.conda/TimeMixer-main/exp/exp_long_term_forecasting.py", line 175, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/.conda/TimeMixer-main/models/TimeMixer.py", line 402, in forward
    dec_out_list = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
  File "/root/.conda/TimeMixer-main/models/TimeMixer.py", line 367, in forecast
    enc_out_list = self.pdm_blocks[i](enc_out_list)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/.conda/TimeMixer-main/models/TimeMixer.py", line 176, in forward
    out_season_list = self.mixing_multi_scale_season(season_list)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/.conda/TimeMixer-main/models/TimeMixer.py", line 62, in forward
    out_low = season_list[1]
IndexError: list index out of range

**Comment by Jpcsnes** [comment]
我也遇到了这个问题，请问你解决了吗

**Comment by kwuking** [comment]
你好 请问执行的是哪一个数据集的脚本呢？

**Comment by Jpcsnes** [comment]
你好，是ETTh1
Traceback (most recent call last):
  File "D:\tool\python\pythonProject\ro\TimeMixer-main\run.py", line 143, in <module>
    exp.train(setting)
  File "D:\tool\python\pythonProject\ro\TimeMixer-main\exp\exp_long_term_forecasting.py", line 169, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tool\python\anaconda\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tool\python\anaconda\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tool\python\pythonProject\ro\TimeMixer-main\models\TimeMixer.py", line 398, in forward
    dec_out_list = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tool\python\pythonProject\ro\TimeMixer-main\models\TimeMixer.py", line 363, in forecast
    enc_out_list = self.pdm_blocks[i](enc_out_list)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tool\python\anaconda\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tool\python\anaconda\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tool\python\pythonProject\ro\TimeMixer-main\models\TimeMixer.py", line 172, in forward
    out_season_list = self.mixing_multi_scale_season(season_list)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tool\python\anaconda\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tool\python\anaconda\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tool\python\pythonProject\ro\TimeMixer-main\models\TimeMixer.py", line 58, in forward
    out_low = season_list[1]
              ~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by kwuking** [comment]
请问是直接执行的脚本呢，还是复制参数执行的呢？

**Comment by kwuking** [comment]
> 你好，是复制参数执行的



> 你好，是复制参数执行的

好的 可以把运行参数发一下嘛

**Comment by kwuking** [comment]
> 这是为什么呢？

请问你也是运行ETTh1脚本出现的报错嘛

**Comment by FutureComming** [comment]
我也遇到了同样的错误，不过是使用自己的数据集，请问你是哪个参数导致的问题呢

**Comment by lkx971216** [comment]
你好 请问是如何解决这个问题的
