### ISSUE TITLE
season_list长度为: 1想问一下我的代码这个长度是1，文中有out_low = season_list[1]就会报错，想问一下是代码哪里出问题了吗

### ISSUE THREAD

**Issue by qq234567890lyj** [kwuking/TimeMixer#47]

**Comment by kwuking** [comment]
你好，请问你是执行的那个脚本？你使用的是哪个数据集呢？

**Comment by qq234567890lyj** [comment]
我使用ETTm1,我直接在run.py进行执行的2

**Comment by qq234567890lyj** [comment]
> 你好，请问你是执行的那个脚本？你使用的是哪个数据集呢？

我使用ETTm1,我直接在run.py进行执行的

**Comment by kwuking** [comment]
> > 你好，请问你是执行的那个脚本？你使用的是哪个数据集呢？
> 
> 我使用ETTm1,我直接在run.py进行执行的

你好可以直接执行shell脚本，在script下的ETTm1对应的运行脚本可以直接sh运行的，我目前执行完成时没有问题的，如果还有问题，可以提供下详细的报错日志。

**Comment by qq234567890lyj** [comment]
> > > 你好，请问你是执行的那个脚本？你使用的是哪个数据集呢？
> > 
> > 
> > 我使用ETTm1,我直接在run.py进行执行的
> 
> 你好可以直接执行shell脚本，在script下的ETTm1对应的运行脚本可以直接sh运行的，我目前执行完成时没有问题的，如果还有问题，可以提供下详细的报错日志。

test 11425
season_list长度为: 1
Traceback (most recent call last):
  File "E:\时间序列\时间序列论文和代码\相似的时间序列模型\TimeMixer\TimeMixer-main\run.py", line 143, in <module>
    exp.train(setting)
  File "E:\时间序列\时间序列论文和代码\相似的时间序列模型\TimeMixer\TimeMixer-main\exp\exp_long_term_forecasting.py", line 169, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "D:\python1\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\python1\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\时间序列\时间序列论文和代码\相似的时间序列模型\TimeMixer\TimeMixer-main\models\TimeMixer.py", line 399, in forward
    dec_out_list = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
  File "E:\时间序列\时间序列论文和代码\相似的时间序列模型\TimeMixer\TimeMixer-main\models\TimeMixer.py", line 364, in forecast
    enc_out_list = self.pdm_blocks[i](enc_out_list)
  File "D:\python1\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\python1\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\时间序列\时间序列论文和代码\相似的时间序列模型\TimeMixer\TimeMixer-main\models\TimeMixer.py", line 173, in forward
    out_season_list = self.mixing_multi_scale_season(season_list)
  File "D:\python1\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\python1\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\时间序列\时间序列论文和代码\相似的时间序列模型\TimeMixer\TimeMixer-main\models\TimeMixer.py", line 59, in forward
    out_low = season_list[1]
IndexError: list index out of range

**Comment by kwuking** [comment]
> exp.train(setting)

看起来是模型参数的问题，请问是直接执行的ETTm1的sh脚本嘛

**Comment by qq234567890lyj** [comment]
> > exp.train(setting)
> 
> 看起来是模型参数的问题，请问是直接执行的ETTm1的sh脚本嘛

可以了，谢谢
