### ISSUE TITLE
RuntimeError in shot_term_forecast/PEMS script

### ISSUE THREAD

**Issue by carusyte** [kwuking/TimeMixer#69]
Encountered the following error running the `bash ./scripts/short_term_forecast/PEMS/TimeMixer.sh`.

OS: MacOS 12.7.6
Python version: 3.12.2 (pyenv)
PyTorch: 2.2.2
CPU: intel

```
>>>>>>>start training : long_term_forecast_PEMS03_none_TimeMixer_PEMS_sl96_pl12_dm128_nh4_el5_dl1_df256_fc3_ebtimeF_dtTrue_Exp_0>>>>>>>>>>>>>>>>>>>>>>>>>>
data file: ./dataset/PEMS/PEMS03.npz
train 15617
data file: ./dataset/PEMS/PEMS03.npz
val 5135
data file: ./dataset/PEMS/PEMS03.npz
test 427
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 286, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jx/ProgramData/git/TimeMixer/run.py", line 157, in <module>
    exp.train(setting)
  File "/Users/jx/ProgramData/git/TimeMixer/exp/exp_long_term_forecasting.py", line 132, in train
    for i, (batch_x, batch_y, batch_x_mark, batch_y_mark) in enumerate(train_loader):
                                                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jx/.pyenv/versions/venv_3.12.2/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 439, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jx/.pyenv/versions/venv_3.12.2/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jx/.pyenv/versions/venv_3.12.2/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1040, in __init__
    w.start()
  File "/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/context.py", line 289, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "/Users/jx/.pyenv/versions/3.12.2/lib/python3.12/multiprocessing/spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
```

**Comment by kwuking** [comment]
Hi, thank you for your attention to our work. This issue seems to be caused by the setting of num_work. You can try setting it to 0.

**Comment by carusyte** [comment]
Confirmed that adding `--num_workers 0` as argument in the shell script is able to solve the issue. Thanks for the prompt reply!
