### ISSUE TITLE
RuntimeError: The size of tensor a (7) must match the size of tensor b (21) at non-singleton dimension 2

### ISSUE THREAD

**Issue by Des-Moines-38** [kwuking/TimeMixer#90]
在ETTh1数据集上训练，指令是sh中的指令，出现以下报错
Traceback (most recent call last):
  File "run.py", line 158, in <module>
    exp.train(setting)
  File "D:\code\TimeMixer-main\exp\exp_long_term_forecasting.py", line 169, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "D:\software\Anaconda\envs\Timemixer\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\code\TimeMixer-main\models\TimeMixer.py", line 517, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
  File "D:\code\TimeMixer-main\models\TimeMixer.py", line 349, in forecast
    x = self.normalize_layers[i](x, 'norm')
  File "D:\software\Anaconda\envs\Timemixer\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\code\TimeMixer-main\layers\StandardNorm.py", line 24, in forward
    x = self._normalize(x)
  File "D:\code\TimeMixer-main\layers\StandardNorm.py", line 53, in _normalize
    x = x * self.affine_weight
RuntimeError: The size of tensor a (7) must match the size of tensor b (21) at non-singleton dimension 2
请问能为这个报错提供些建议吗，谢谢

**Comment by jocelyn2002** [comment]
请问你是如何解决的呢
